//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AigioSoft.Common.Mvc.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AigioSoft.Common.Mvc.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;401 - 未授权: 由于凭据无效，访问被拒绝。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        /// #content h1  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _401 {
            get {
                return ResourceManager.GetString("_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;403 - 禁止访问: 访问被拒绝。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        /// #content h1 {
        /// fo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _403 {
            get {
                return ResourceManager.GetString("_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;404 - 找不到文件或目录。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        /// #content h1 {
        /// font- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _404 {
            get {
                return ResourceManager.GetString("_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;405 - 不允许用于访问此页的 HTTP 谓词。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        /// #content h1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _405 {
            get {
                return ResourceManager.GetString("_405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;406 - 客户端浏览器不接受 MIME 类型的请求页面。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        /// #conten [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _406 {
            get {
                return ResourceManager.GetString("_406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;412 - 在 Web 服务器上进行评估时，由客户端设置的前提条件失败。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _412 {
            get {
                return ResourceManager.GetString("_412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;501 - 头值指定了无法实现的方法。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        /// #content h1 {
        /// f [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _501 {
            get {
                return ResourceManager.GetString("_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;head&gt;
        /// &lt;title&gt;502 - Web 服务器在作为网关或代理服务器时收到了无效响应。&lt;/title&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;style type=&quot;text/css&quot;&gt;
        /// html {
        /// height: 100%;
        /// width: 100%;
        /// }
        /// #feature {
        /// width: 960px;
        /// margin: 95px auto 0 auto;
        /// overflow: auto;
        /// }
        /// #content {
        /// font-family: &quot;Segoe UI&quot;;
        /// font-weight: normal;
        /// font-size: 22px;
        /// color: #ffffff;
        /// float: left;
        /// width: 460px;
        /// margin-top: 68px;
        /// margin-left: 0px;
        /// vertical-align: middle;
        /// }
        /// #co [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _502 {
            get {
                return ResourceManager.GetString("_502", resourceCulture);
            }
        }
    }
}
